"""Evidence trail formatting for auto-PR descriptions.

Generates structured markdown PR bodies and commit messages that
link the full audit chain: anomaly -> investigation -> fix -> PR.
"""

import logging
from typing import Any

from beeper_investigator.context import InvestigationContext

logger = logging.getLogger(__name__)


class EvidenceTrailFormatter:
    """Formats PR bodies and commit messages with investigation evidence."""

    def format_pr_body(
        self,
        context: InvestigationContext,
        pipeline_metadata: dict[str, Any],
        fix_description: str,
    ) -> str:
        """Generate a markdown PR body with full evidence trail.

        Args:
            context: Current investigation context.
            pipeline_metadata: Accumulated data from prior pipeline steps.
            fix_description: Human-readable description of the fix.

        Returns:
            Formatted markdown string.
        """
        sections: list[str] = []

        # Header
        sections.append(
            f"## Beeper Auto-Fix: {context.service} — {context.condition}\n"
        )

        # Fix description
        sections.append(f"**Fix:** {fix_description}\n")

        # Investigation summary
        customer_impacting = pipeline_metadata.get("customer_impacting", "unknown")
        sections.append(
            "### Investigation Summary\n"
            f"- **Investigation ID:** {context.investigation_id}\n"
            f"- **Service:** {context.service}\n"
            f"- **Condition:** {context.condition}\n"
            f"- **Severity:** {context.severity}\n"
            f"- **Namespace:** {context.namespace}\n"
            f"- **Customer Impacting:** {customer_impacting}\n"
        )

        # Root cause analysis
        hypothesis = pipeline_metadata.get("root_cause_hypothesis", "")
        if hypothesis:
            confidence_level = pipeline_metadata.get("confidence_level", "unknown")
            confidence_pct = pipeline_metadata.get("confidence_percentage", "N/A")
            evidence_items = pipeline_metadata.get("supporting_evidence", [])

            evidence_text = ""
            if evidence_items:
                evidence_lines = [f"- {item}" for item in evidence_items]
                evidence_text = (
                    "\n**Supporting Evidence:**\n" + "\n".join(evidence_lines) + "\n"
                )

            sections.append(
                "### Root Cause Analysis\n"
                f"**Hypothesis:** {hypothesis}\n"
                f"**Confidence:** {confidence_level} ({confidence_pct}%)\n"
                f"{evidence_text}"
            )

        # Log correlation evidence
        signal_summary = pipeline_metadata.get("signal_summary", "")
        if signal_summary:
            layers = pipeline_metadata.get("layers_queried", [])
            layers_text = ", ".join(layers) if layers else "N/A"
            sections.append(
                "### Log Correlation Evidence\n"
                f"{signal_summary}\n\n"
                f"**Data Sources Queried:** {layers_text}\n"
            )

        # Production conditions
        sections.append(
            "### Production Conditions\n"
            f"- **Severity:** {context.severity}\n"
            f"- **Customer Impacting:** {customer_impacting}\n"
        )

        # Advisory test plan (if available from step 8)
        if pipeline_metadata.get("test_plan_generated"):
            steps = pipeline_metadata.get("verification_steps", [])
            if steps:
                step_lines = []
                for s in steps:
                    if isinstance(s, dict):
                        num = s.get("step_number", "?")
                        title = s.get("title", "Untitled")
                        action = s.get("action", "")
                        step_lines.append(f"{num}. **{title}** — {action}")
                    else:
                        logger.warning(
                            "Skipping non-dict verification step: %s", type(s).__name__
                        )
                sections.append(
                    "### Advisory Test Plan\n" + "\n".join(step_lines) + "\n"
                )

        # Audit trail
        sections.append(
            "### Audit Trail\n"
            f"anomaly ({context.condition}) → investigation ({context.investigation_id})"
            f" → fix (this PR) → verification (pending)\n"
        )

        # Footer
        sections.append(
            "---\n"
            f"*Generated by [Beeper](https://beeper.dev) "
            f"| Investigation {context.investigation_id}*"
        )

        return "\n".join(sections)

    def format_commit_message(
        self,
        context: InvestigationContext,
        fix_description: str,
    ) -> str:
        """Generate a structured commit message.

        Args:
            context: Current investigation context.
            fix_description: Short description of the fix.

        Returns:
            Formatted commit message string.
        """
        short_desc = fix_description.split("\n")[0][:72] if fix_description else "auto-fix"
        return (
            f"fix({context.service}): {short_desc}\n\n"
            f"Investigation: {context.investigation_id}\n"
            f"Condition: {context.condition}\n"
            f"Severity: {context.severity}"
        )
