apiVersion: v1
kind: Service
metadata:
  name: {{ include "beeper.fullname" . }}-operator
  labels:
    {{- include "beeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  type: ClusterIP
  selector:
    {{- include "beeper.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  ports:
    - name: http
      port: 8080
      targetPort: health
      protocol: TCP
