apiVersion: beeper.dev/v1
kind: ServiceLevel
metadata:
  name: otel-productcatalog-slo
  namespace: otel-demo
  labels:
    app.kubernetes.io/part-of: otel-demo
spec:
  service: "product-catalog"
  sli:
    type: availability
    metric: "rpc_server_duration_milliseconds_count"
    good_selector: '{service_name="product-catalog",rpc_grpc_status_code="0"}'
    total_selector: '{service_name="product-catalog"}'
  objective:
    target: 0.999
    window: "30m"
  burn_rate_alerts:
    - severity: warning
      short_window: "5m"
      long_window: "1h"
      factor: 14.4
    - severity: critical
      short_window: "2m"
      long_window: "15m"
      factor: 14.4
