#!/usr/bin/env python3
"""Seed Qdrant with sample KB entries for local development.

This script populates the 'knowledge' and 'investigations' collections
with sample data for testing and development purposes.

Usage:
    python scripts/seed_kb.py [--host HOST] [--port PORT]

Environment variables:
    QDRANT_HOST: Qdrant server host (default: localhost)
    QDRANT_PORT: Qdrant server port (default: 6333)
"""

import argparse
import logging
import os
import random
import sys
import uuid
from datetime import datetime, timezone

from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Vector dimension (must match init-collections.py)
VECTOR_DIM = 1536


def generate_placeholder_embedding(entry_id: str) -> list[float]:
    """Generate a placeholder embedding vector for development.

    In production, these would be generated by an embedding model.
    For development, we use random vectors seeded by entry_id for
    reproducible but unique embeddings per entry.

    Args:
        entry_id: Unique identifier used to seed the random generator
    """
    # Seed based on entry_id hash for unique but reproducible embeddings
    random.seed(hash(entry_id) % (2**32))
    return [random.uniform(-1, 1) for _ in range(VECTOR_DIM)]


# Sample runbook entries (OTel Astronomy Shop services)
SAMPLE_RUNBOOKS = [
    {
        "entry_id": "rb-001",
        "entry_type": "runbook",
        "title": "Payment Service Failure Investigation",
        "content": """# Payment Service Failure Investigation Runbook

## Symptoms
- Checkout requests failing with payment errors
- Increased error rate on paymentservice
- Customers unable to complete orders

## Investigation Steps
1. Check paymentservice logs for charge method errors
2. Query Prometheus: rate(http_server_request_duration_seconds_count{service_name="paymentservice",http_status_code=~"5.."}[5m])
3. Check if paymentServiceFailure feature flag is enabled in flagd
4. Review distributed traces in Jaeger for failed checkout flows

## Common Root Causes
- Feature flag paymentServiceFailure enabled (fault injection)
- Upstream payment gateway timeout
- Invalid payment data from checkoutservice

## Resolution Actions
- Disable paymentServiceFailure feature flag if enabled
- Restart paymentservice pods if unresponsive
- Check checkoutservice for malformed payment requests
""",
        "service": "paymentservice",
        "created_at": "2026-01-15T10:00:00Z",
    },
    {
        "entry_id": "rb-002",
        "entry_type": "runbook",
        "title": "Cart Service Error Handling",
        "content": """# Cart Service Error Handling Runbook

## Symptoms
- EmptyCart operations failing
- Cart state inconsistencies
- Frontend showing stale cart data

## Investigation Steps
1. Check cartservice logs for gRPC errors
2. Query Prometheus: rate(http_server_request_duration_seconds_count{service_name="cartservice",http_status_code=~"5.."}[5m])
3. Check Valkey (Redis) cache connectivity from cartservice
4. Check if cartServiceFailure feature flag is enabled

## Common Root Causes
- Feature flag cartServiceFailure enabled (fault injection)
- Valkey cache connection timeout or eviction
- Cart data serialization errors

## Resolution Actions
- Disable cartServiceFailure feature flag if enabled
- Restart cartservice pods
- Check Valkey health and memory usage
""",
        "service": "cartservice",
        "created_at": "2026-01-20T14:30:00Z",
    },
    {
        "entry_id": "rb-003",
        "entry_type": "runbook",
        "title": "Kafka Queue Problems Investigation",
        "content": """# Kafka Queue Problems Investigation Runbook

## Symptoms
- Order processing delays
- Kafka consumer lag increasing
- Checkout completes but order confirmation delayed

## Investigation Steps
1. Check Kafka consumer group lag metrics
2. Review checkoutservice and accountingservice logs for Kafka errors
3. Check if kafkaQueueProblems feature flag is enabled
4. Monitor Kafka broker health and partition distribution

## Common Root Causes
- Feature flag kafkaQueueProblems enabled (queue overload + consumer delays)
- Kafka broker resource exhaustion
- Consumer processing too slow for incoming rate
- Network partition between services and Kafka

## Resolution Actions
- Disable kafkaQueueProblems feature flag if enabled
- Scale Kafka consumers (increase accountingservice replicas)
- Check Kafka broker disk and memory usage
- Restart affected consumer pods
""",
        "service": "kafka",
        "created_at": "2026-01-22T09:15:00Z",
    },
    {
        "entry_id": "rb-004",
        "entry_type": "runbook",
        "title": "Frontend Slow Loading Investigation",
        "content": """# Frontend Slow Loading Investigation Runbook

## Symptoms
- Page load times significantly increased
- Images loading slowly or timing out
- User-facing latency SLO violations

## Investigation Steps
1. Check frontend p99 latency: histogram_quantile(0.99, rate(http_server_request_duration_seconds_bucket{service_name="frontend"}[5m]))
2. Check if imageSlowLoad feature flag is enabled
3. Review image provider (nginx) response times
4. Check frontend proxy (Envoy) for upstream timeouts

## Common Root Causes
- Feature flag imageSlowLoad enabled (deliberate image delays)
- Image provider resource constraints
- Frontend proxy connection limits
- CDN or network latency

## Resolution Actions
- Disable imageSlowLoad feature flag if enabled
- Restart image provider pods
- Check frontend proxy configuration and limits
""",
        "service": "frontend",
        "created_at": "2026-01-25T16:45:00Z",
    },
    {
        "entry_id": "rb-005",
        "entry_type": "runbook",
        "title": "Ad Service High CPU Investigation",
        "content": """# Ad Service High CPU Investigation Runbook

## Symptoms
- adservice CPU usage spiking to limits
- Ad loading slow or timing out
- Pod throttling or OOMKill events

## Investigation Steps
1. Check adservice CPU metrics: container_cpu_usage_seconds_total{container="adservice"}
2. Check if adServiceHighCpu feature flag is enabled
3. Review adservice JVM metrics (heap usage, GC pressure)
4. Check pod resource limits vs actual usage

## Common Root Causes
- Feature flag adServiceHighCpu enabled (fault injection)
- JVM garbage collection pressure
- Inefficient ad matching algorithm under load
- Resource limits too low for traffic volume

## Resolution Actions
- Disable adServiceHighCpu feature flag if enabled
- Increase adservice CPU/memory limits
- Restart adservice pods to clear JVM state
- Scale adservice horizontally if load-related
""",
        "service": "adservice",
        "created_at": "2026-01-28T11:00:00Z",
    },
]

# Sample completed investigation entries (OTel Astronomy Shop)
SAMPLE_INVESTIGATIONS = [
    {
        "investigation_id": "inv-001",
        "status": "resolved",
        "service": "paymentservice",
        "started_at": "2026-01-28T08:30:00Z",
        "title": "Payment Processing Failures During Checkout",
        "root_cause": "paymentServiceFailure feature flag was enabled, causing charge method to return errors",
        "resolution": "Disabled paymentServiceFailure feature flag via flagd; confirmed error rate returned to baseline",
    },
    {
        "investigation_id": "inv-002",
        "status": "resolved",
        "service": "cartservice",
        "started_at": "2026-01-30T14:00:00Z",
        "title": "Cart Service EmptyCart Errors",
        "root_cause": "cartServiceFailure feature flag enabled, causing EmptyCart gRPC method to fail",
        "resolution": "Disabled cartServiceFailure flag; restarted cartservice pods to clear stale state",
    },
    {
        "investigation_id": "inv-003",
        "status": "resolved",
        "service": "checkoutservice",
        "started_at": "2026-02-01T11:15:00Z",
        "title": "Order Confirmation Delays from Kafka Backlog",
        "root_cause": "kafkaQueueProblems feature flag caused queue overload and consumer-side delays",
        "resolution": "Disabled kafkaQueueProblems flag; consumer lag cleared within 2 minutes",
    },
]


def upsert_knowledge_entries(client: QdrantClient) -> int:
    """Upsert sample runbook entries into the knowledge collection.

    Returns the number of entries upserted.
    """
    points = []
    for runbook in SAMPLE_RUNBOOKS:
        point = PointStruct(
            id=str(uuid.uuid5(uuid.NAMESPACE_DNS, runbook["entry_id"])),
            vector=generate_placeholder_embedding(runbook["entry_id"]),
            payload={
                "entry_id": runbook["entry_id"],
                "entry_type": runbook["entry_type"],
                "title": runbook["title"],
                "content": runbook["content"],
                "service": runbook["service"],
                "created_at": runbook["created_at"],
            },
        )
        points.append(point)
        logger.info(f"  Prepared runbook: {runbook['title']}")

    client.upsert(collection_name="knowledge", points=points, wait=True)
    return len(points)


def upsert_investigation_entries(client: QdrantClient) -> int:
    """Upsert sample investigation entries into the investigations collection.

    Returns the number of entries upserted.
    """
    points = []
    for inv in SAMPLE_INVESTIGATIONS:
        point = PointStruct(
            id=str(uuid.uuid5(uuid.NAMESPACE_DNS, inv["investigation_id"])),
            vector=generate_placeholder_embedding(inv["investigation_id"]),
            payload={
                "investigation_id": inv["investigation_id"],
                "status": inv["status"],
                "service": inv["service"],
                "started_at": inv["started_at"],
                "title": inv["title"],
                "root_cause": inv["root_cause"],
                "resolution": inv["resolution"],
            },
        )
        points.append(point)
        logger.info(f"  Prepared investigation: {inv['title']}")

    client.upsert(collection_name="investigations", points=points, wait=True)
    return len(points)


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Seed Qdrant with sample KB entries for development"
    )
    parser.add_argument(
        "--host",
        default=os.getenv("QDRANT_HOST", "localhost"),
        help="Qdrant server host (default: localhost)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.getenv("QDRANT_PORT", "6333")),
        help="Qdrant server port (default: 6333)",
    )
    args = parser.parse_args()

    logger.info(f"Connecting to Qdrant at {args.host}:{args.port}")

    try:
        client = QdrantClient(host=args.host, port=args.port)
        client.get_collections()
        logger.info("Connected to Qdrant successfully")
    except Exception as e:
        logger.error(f"Failed to connect to Qdrant: {e}")
        return 1

    # Seed knowledge collection (runbooks)
    logger.info("Seeding knowledge collection with runbooks...")
    try:
        kb_count = upsert_knowledge_entries(client)
        logger.info(f"Upserted {kb_count} runbook entries")
    except Exception as e:
        logger.error(f"Failed to seed knowledge collection: {e}")
        return 1

    # Seed investigations collection
    logger.info("Seeding investigations collection with sample data...")
    try:
        inv_count = upsert_investigation_entries(client)
        logger.info(f"Upserted {inv_count} investigation entries")
    except Exception as e:
        logger.error(f"Failed to seed investigations collection: {e}")
        return 1

    logger.info(f"Seeding complete! Total entries: {kb_count + inv_count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
