#!/usr/bin/env python3
"""Seed Qdrant with sample KB entries for local development.

This script populates the 'knowledge' and 'investigations' collections
with sample data for testing and development purposes.

Usage:
    python scripts/seed_kb.py [--host HOST] [--port PORT]

Environment variables:
    QDRANT_HOST: Qdrant server host (default: localhost)
    QDRANT_PORT: Qdrant server port (default: 6333)
"""

import argparse
import logging
import os
import random
import sys
import uuid
from datetime import datetime, timezone

from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Vector dimension (must match init-collections.py)
VECTOR_DIM = 1536


def generate_placeholder_embedding(entry_id: str) -> list[float]:
    """Generate a placeholder embedding vector for development.

    In production, these would be generated by an embedding model.
    For development, we use random vectors seeded by entry_id for
    reproducible but unique embeddings per entry.

    Args:
        entry_id: Unique identifier used to seed the random generator
    """
    # Seed based on entry_id hash for unique but reproducible embeddings
    random.seed(hash(entry_id) % (2**32))
    return [random.uniform(-1, 1) for _ in range(VECTOR_DIM)]


# Sample runbook entries
SAMPLE_RUNBOOKS = [
    {
        "entry_id": "rb-001",
        "entry_type": "runbook",
        "title": "High CPU Usage Investigation",
        "content": """# High CPU Usage Investigation Runbook

## Symptoms
- CPU usage consistently above 80% for more than 5 minutes
- Increased response latency
- Potential service degradation

## Investigation Steps
1. Identify the process consuming CPU: `top -o %CPU`
2. Check for runaway queries or infinite loops
3. Review recent deployments
4. Check for traffic spikes in metrics

## Common Root Causes
- Inefficient database queries
- Memory pressure causing GC thrashing
- Traffic spike without autoscaling
- Bug in recent deployment

## Resolution Actions
- Scale horizontally if traffic-related
- Rollback if deployment-related
- Optimize queries if database-related
""",
        "service": "payments",
        "created_at": "2026-01-15T10:00:00Z",
    },
    {
        "entry_id": "rb-002",
        "entry_type": "runbook",
        "title": "Database Connection Pool Exhaustion",
        "content": """# Database Connection Pool Exhaustion Runbook

## Symptoms
- "Connection pool exhausted" errors in logs
- Increased latency on database operations
- Timeout errors from application

## Investigation Steps
1. Check current connection count: `SELECT count(*) FROM pg_stat_activity`
2. Identify long-running queries
3. Check for connection leaks in application logs
4. Review pool configuration

## Common Root Causes
- Connection leak in application code
- Long-running transactions
- Sudden traffic spike
- Pool size too small for load

## Resolution Actions
- Restart affected pods to release connections
- Kill long-running queries
- Increase pool size if warranted
- Deploy fix for connection leak
""",
        "service": "database",
        "created_at": "2026-01-20T14:30:00Z",
    },
    {
        "entry_id": "rb-003",
        "entry_type": "runbook",
        "title": "Kubernetes Pod CrashLoopBackOff",
        "content": """# Kubernetes Pod CrashLoopBackOff Runbook

## Symptoms
- Pod status shows CrashLoopBackOff
- Container restarts increasing
- Service unavailability

## Investigation Steps
1. Check pod events: `kubectl describe pod <name>`
2. Review container logs: `kubectl logs <pod> --previous`
3. Check resource limits and requests
4. Verify ConfigMaps and Secrets are mounted

## Common Root Causes
- Application startup failure
- Missing configuration or secrets
- Resource limits too restrictive
- Liveness probe misconfiguration

## Resolution Actions
- Fix application startup issue
- Update ConfigMaps/Secrets
- Adjust resource limits
- Fix liveness probe configuration
""",
        "service": "kubernetes",
        "created_at": "2026-01-22T09:15:00Z",
    },
    {
        "entry_id": "rb-004",
        "entry_type": "runbook",
        "title": "API Gateway 502 Bad Gateway Errors",
        "content": """# API Gateway 502 Bad Gateway Errors Runbook

## Symptoms
- Clients receiving 502 errors
- Backend services may be healthy
- Intermittent failures

## Investigation Steps
1. Check backend service health endpoints
2. Review API gateway logs for upstream errors
3. Check network connectivity between gateway and backends
4. Verify load balancer configuration

## Common Root Causes
- Backend service unhealthy or restarting
- Network timeout between gateway and backend
- Misconfigured health checks
- Backend returning invalid responses

## Resolution Actions
- Restart unhealthy backend pods
- Increase timeout settings
- Fix health check configuration
- Debug backend response format
""",
        "service": "api-gateway",
        "created_at": "2026-01-25T16:45:00Z",
    },
]

# Sample completed investigation entries
SAMPLE_INVESTIGATIONS = [
    {
        "investigation_id": "inv-001",
        "status": "resolved",
        "service": "payments",
        "started_at": "2026-01-28T08:30:00Z",
        "title": "Payment Service Latency Spike",
        "root_cause": "Database connection pool exhaustion due to long-running transaction",
        "resolution": "Identified and killed blocking transaction; implemented query timeout",
    },
    {
        "investigation_id": "inv-002",
        "status": "resolved",
        "service": "api-gateway",
        "started_at": "2026-01-30T14:00:00Z",
        "title": "API Gateway Intermittent 502 Errors",
        "root_cause": "Backend health check misconfiguration causing false positives",
        "resolution": "Updated health check endpoint and timeout configuration",
    },
    {
        "investigation_id": "inv-003",
        "status": "resolved",
        "service": "orders",
        "started_at": "2026-02-01T11:15:00Z",
        "title": "Order Processing Failures",
        "root_cause": "Kafka consumer lag due to partition rebalancing",
        "resolution": "Increased consumer instances and optimized partition assignment",
    },
]


def upsert_knowledge_entries(client: QdrantClient) -> int:
    """Upsert sample runbook entries into the knowledge collection.

    Returns the number of entries upserted.
    """
    points = []
    for runbook in SAMPLE_RUNBOOKS:
        point = PointStruct(
            id=str(uuid.uuid5(uuid.NAMESPACE_DNS, runbook["entry_id"])),
            vector=generate_placeholder_embedding(runbook["entry_id"]),
            payload={
                "entry_id": runbook["entry_id"],
                "entry_type": runbook["entry_type"],
                "title": runbook["title"],
                "content": runbook["content"],
                "service": runbook["service"],
                "created_at": runbook["created_at"],
            },
        )
        points.append(point)
        logger.info(f"  Prepared runbook: {runbook['title']}")

    client.upsert(collection_name="knowledge", points=points, wait=True)
    return len(points)


def upsert_investigation_entries(client: QdrantClient) -> int:
    """Upsert sample investigation entries into the investigations collection.

    Returns the number of entries upserted.
    """
    points = []
    for inv in SAMPLE_INVESTIGATIONS:
        point = PointStruct(
            id=str(uuid.uuid5(uuid.NAMESPACE_DNS, inv["investigation_id"])),
            vector=generate_placeholder_embedding(inv["investigation_id"]),
            payload={
                "investigation_id": inv["investigation_id"],
                "status": inv["status"],
                "service": inv["service"],
                "started_at": inv["started_at"],
                "title": inv["title"],
                "root_cause": inv["root_cause"],
                "resolution": inv["resolution"],
            },
        )
        points.append(point)
        logger.info(f"  Prepared investigation: {inv['title']}")

    client.upsert(collection_name="investigations", points=points, wait=True)
    return len(points)


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Seed Qdrant with sample KB entries for development"
    )
    parser.add_argument(
        "--host",
        default=os.getenv("QDRANT_HOST", "localhost"),
        help="Qdrant server host (default: localhost)",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.getenv("QDRANT_PORT", "6333")),
        help="Qdrant server port (default: 6333)",
    )
    args = parser.parse_args()

    logger.info(f"Connecting to Qdrant at {args.host}:{args.port}")

    try:
        client = QdrantClient(host=args.host, port=args.port)
        client.get_collections()
        logger.info("Connected to Qdrant successfully")
    except Exception as e:
        logger.error(f"Failed to connect to Qdrant: {e}")
        return 1

    # Seed knowledge collection (runbooks)
    logger.info("Seeding knowledge collection with runbooks...")
    try:
        kb_count = upsert_knowledge_entries(client)
        logger.info(f"Upserted {kb_count} runbook entries")
    except Exception as e:
        logger.error(f"Failed to seed knowledge collection: {e}")
        return 1

    # Seed investigations collection
    logger.info("Seeding investigations collection with sample data...")
    try:
        inv_count = upsert_investigation_entries(client)
        logger.info(f"Upserted {inv_count} investigation entries")
    except Exception as e:
        logger.error(f"Failed to seed investigations collection: {e}")
        return 1

    logger.info(f"Seeding complete! Total entries: {kb_count + inv_count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
